# Especificar la imagen base
FROM nginx
MAINTAINER Crivmar "carlosrivero1988@gmail.com"
# Añadir fichero local al directorio del contenedor
ADD pagina /usr/share/nginx/html
# Puertos abiertos en el contenedor
EXPOSE 80
EXPOSE 443
